// Generated by CoffeeScript 1.6.3
(function() {
  var tags, users;
  users = [
    {
      uid: '001',
      name: 'Nicolas Torres'
    }, {
      uid: '002',
      name: 'Guillaume Beck'
    }, {
      uid: '003',
      name: 'Jean-Michel Didon'
    }, {
      uid: '004',
      name: 'Elise Berthet'
    }, {
      uid: '005',
      name: 'Rémi Fayolle'
    }
  ];
  return tags = ['development', 'design', 'ux', 'slug', 'project', 'management', 'form', 'users'];
})();
