synappseApp = angular.module 'synappseTranslate', [ 'pascalprecht.translate' ]
synappseApp.config ['$translateProvider', ( $translateProvider ) -> 
  
  $translateProvider.translations 'en',
     SELECT: 'Select a project'
     CREATE_PLACEHOLDER: 'New project name'
     CREATE: 'Create'
     SYNCED: 'synced'
     TAB_DUES: 'Dues'
     TAB_OTHERS: 'Others'
     TAB_ARCHIVED: 'Archived'
     FORM_TASK_PLACEHOLDER: 'What do you have to do?'
     NO_MORE_TASKS: 'No more tasks'
     NO_TASKS: 'No tasks'
     TODO: 'Todo'
     IN_PROGRESS: 'In progress'
     ADVANCED: 'Advanced'
     DONE: 'Done'
     ARCHIVED: 'Archived'
     NEW_TASK: 'New task'
     CANCEL: 'Cancel'
     HIDE_CALENDAR: 'Hide calendar'
     SET_DUE_DATE: 'Set due date'
     UPDATE: 'Update'
     MON: 'M'
     TUE: 'T'
     WED: 'W'
     THU: 'T'
     FRI: 'F'
     SAT: 'S'
     SUN: 'S'
  
  $translateProvider.translations 'fr',
    SELECT: 'Choisir un projet'
    CREATE_PLACEHOLDER: 'Nom du nouveau projet'
    CREATE: 'Créer'
    SYNCED: 'à jour'
    TAB_DUES: 'Datées'
    TAB_OTHERS: 'Autres'
    TAB_ARCHIVED: 'Archivées'
    FORM_TASK_PLACEHOLDER: 'Qu\'avez-vous à faire ?'
    NO_MORE_TASKS: 'Il n\'y a plus de tâches'
    NO_TASKS: 'Aucune tâche'
    TODO: 'À faire'
    IN_PROGRESS: 'En cours'
    ADVANCED: 'Avancée'
    DONE: 'Terminée'
    ARCHIVED: 'Archivée'
    NEW_TASK: 'Nouvelle tâche'
    CANCEL: 'Annuler'
    HIDE_CALENDAR: 'Masquer cal.'
    SET_DUE_DATE: 'Date limite'
    UPDATE: 'Enregistrer'
    MON: 'L'
    TUE: 'M'
    WED: 'M'
    THU: 'J'
    FRI: 'V'
    SAT: 'S'
    SUN: 'D'
    January: 'Janvier'
    February: 'Février'
    March: 'Mars'
    April: 'Avril'
    May: 'Mai'
    June: 'Juin'
    July: 'Juillet'
    August: 'Août'
    September: 'Septembre'
    October: 'Octobre'
    November: 'Novembre'
    December: 'Décembre'
    Jan: 'Jan'
    Feb: 'Fév'
    Mar: 'Mars'
    Apr: 'Avr'
    May: 'Mai'
    June: 'Juin'
    July: 'Juil'
    Aug: 'Août'
    Sep: 'Sep'
    Oct: 'Oct'
    Nov: 'Nov'
    Dec: 'Déc'
    Today: 'Aujourd\'hui'
    
  $translateProvider.preferredLanguage 'en'
  
]