synappseApp = angular.module 'synappseTranslate', [ 'pascalprecht.translate' ]
synappseApp.config ['$translateProvider', ( $translateProvider ) ->

  $translateProvider.translations 'en',
    SELECT: 'Select a project'
    SHARE: 'Share'
    EDIT: 'Edit name'

    FAQ_SHARE_TITLE: 'How do I share a project?'
    FAQ_SHARE_ANSWER_1: 'Click on the “share” button next to a project.'
    FAQ_SHARE_ANSWER_2: 'Once in Dropbox website, click on the ”Share” button on the top right corner.'
    FAQ_SHARE_ANSWER_3: 'Add your friend\'s email.'
    FAQ_SHARE_ANSWER_4: 'Tell them to move the shared folder into Synappse/ folder once they accepted the invitation.'
    FAQ_SHARE_ANSWER_5: 'It\'s done!'
    FAQ_DELETE_TITLE: 'How do I delete a project?'
    FAQ_DELETE_ANSWER: 'Just delete the matching folder. Your projects are located in your Dropbox/Synappse/ folder.'

    TASKS: 'Tasks'
    FILES: 'Files'
    DISCUSSIONS: 'Discussions'

    CREATE_PLACEHOLDER: 'New project name'
    CREATE: 'Create'
    SYNCED: 'Synced'
    TAB_DUES: 'Dues'
    TAB_OTHERS: 'Others'
    TAB_ARCHIVED: 'Archived'
    FORM_TASK_PLACEHOLDER: 'What do you have to do?'
    NO_MORE_TASKS: 'No more tasks'
    NO_TASKS: 'No tasks'
    TODO: 'To do'
    IN_PROGRESS: 'In progress'
    ADVANCED: 'Advanced'
    DONE: 'Done'
    ARCHIVED: 'Archived'
    NEW_TASK: 'New task'
    CANCEL: 'Cancel'
    DELETE: 'Delete'
    HIDE_CALENDAR: 'Hide calendar'
    SET_DUE_DATE: 'Set due date'
    UPDATE: 'Update'
    MON: 'M'
    TUE: 'T'
    WED: 'W'
    THU: 'T'
    FRI: 'F'
    SAT: 'S'
    SUN: 'S'
    TODAY: 'Today'
    NO_DUE: 'No due'

    REPORT: 'Report a bug'

  $translateProvider.translations 'fr',
    SELECT: 'Choisir un projet'
    SHARE: 'Partager'
    EDIT: 'Éditer le nom'

    TASKS: 'Tâches'
    FILES: 'Fichiers'
    DISCUSSIONS: 'Discussions'

    FAQ_SHARE_TITLE: 'Comment partager un projet ?'
    FAQ_SHARE_ANSWER_1: 'Cliquer sur “partager” à côté d\'un projet.'
    FAQ_SHARE_ANSWER_2: 'Une fois sur le site Dropbox, cliquez sur "Share" en haut à droite'
    FAQ_SHARE_ANSWER_3: 'Ajoutez l\'email de votre ami(e).'
    FAQ_SHARE_ANSWER_4: 'Dites-lui de déplacer le fichier partagé dans le dossier Synappse/ une fois l\'invitation acceptée.'
    FAQ_SHARE_ANSWER_5: 'Et voilà !'
    FAQ_DELETE_TITLE: 'Comment supprimer un projet ?'
    FAQ_DELETE_ANSWER: 'Il suffit de supprimer le dossier correspondant. Vos projets sont situdés dans le dossier Dropbox/Synappse/.'

    CREATE_PLACEHOLDER: 'Nom du nouveau projet'
    CREATE: 'Créer'
    SYNCED: 'à jour'
    TAB_DUES: 'Datées'
    TAB_OTHERS: 'Autres'
    TAB_ARCHIVED: 'Archivées'
    FORM_TASK_PLACEHOLDER: 'Qu\'avez-vous à faire ?'
    NO_MORE_TASKS: 'Il n\'y a plus de tâches'
    NO_TASKS: 'Aucune tâche'
    TODO: 'À faire'
    IN_PROGRESS: 'En cours'
    ADVANCED: 'Avancée'
    DONE: 'Terminée'
    ARCHIVED: 'Archivée'
    NEW_TASK: 'Nouvelle tâche'
    CANCEL: 'Annuler'
    DELETE: 'Supprimer'
    HIDE_CALENDAR: 'Masquer cal.'
    SET_DUE_DATE: 'Date limite'
    UPDATE: 'Enregistrer'
    MON: 'L'
    TUE: 'M'
    WED: 'M'
    THU: 'J'
    FRI: 'V'
    SAT: 'S'
    SUN: 'D'
    January: 'Janvier'
    February: 'Février'
    March: 'Mars'
    April: 'Avril'
    May: 'Mai'
    June: 'Juin'
    July: 'Juillet'
    August: 'Août'
    September: 'Septembre'
    October: 'Octobre'
    November: 'Novembre'
    December: 'Décembre'
    Jan: 'Jan'
    Feb: 'Fév'
    Mar: 'Mars'
    Apr: 'Avr'
    May: 'Mai'
    June: 'Juin'
    July: 'Juil'
    Aug: 'Août'
    Sep: 'Sep'
    Oct: 'Oct'
    Nov: 'Nov'
    Dec: 'Déc'
    TODAY: 'Aujourd\'hui'
    NO_DUE: 'Non datée'

    REPORT: 'Signaler un problème'

  $translateProvider.preferredLanguage 'en'

]